### ISSUE TITLE
Problem z kompilacją kodu, zmienna globalna currentlyOpenedList

### ISSUE THREAD

**Issue by bartoszzak** [eSqadron/3.5-KBDK_SA#1]
![image](https://user-images.githubusercontent.com/62252217/83910215-733d7180-a76a-11ea-9581-63510f6a048f.png)
Treść błędu

![image](https://user-images.githubusercontent.com/62252217/83910050-2f4a6c80-a76a-11ea-9472-e47413bfcef8.png)
Konfiguracja środowiska PyCharm

**Comment by eSqadron** [comment]
Błąd jest spowodowany starą wersją pythona, na wersji 3.8 błąd nie występuje. Pod tą wersją był tworzony ten kawałek kodu i rzeczywiście, gdy cofnąłem się do wersji 3.7 błąd się pojawił także u mnie.
