### ISSUE TITLE
Przycisk zamykający obecnie otwartą listę

### ISSUE THREAD

**Issue by eSqadron** [eSqadron/3.5-KBDK_SA#2]
Przycisk closeListButton zamykający obecnie otwartą listę nie działa. Jest to błąd najprawdopodbniej związany z zamieszczoną tam Lambdą.

**Comment by bartoszzak** [comment]
![image](https://user-images.githubusercontent.com/62252217/85229756-ffe36300-b3eb-11ea-80ba-0ca4e4704ef9.png)
Błąd był spowodowany brakiem nawiasu pokazanym na screenie.
